opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/public-release-reloaded/parallel"
bug-reports: "https://github.com/public-release-reloaded/parallel/issues"
dev-repo: "git+https://github.com/public-release-reloaded/parallel.git#v0.18_preview.130.100+614+reloaded"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/parallel/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.5.0"}
  "async" {>= "v0.18~" & < "v0.19~"}
  "await" {>= "v0.18~" & < "v0.19~"}
  "base" {>= "v0.18~" & < "v0.19~"}
  "base_bigstring" {>= "v0.18~" & < "v0.19~"}
  "bignum" {>= "v0.18~" & < "v0.19~"}
  "concurrent" {>= "v0.18~" & < "v0.19~"}
  "core" {>= "v0.18~" & < "v0.19~"}
  "expect_test_helpers_core" {>= "v0.18~" & < "v0.19~"}
  "handled_effect" {>= "v0.18~" & < "v0.19~"}
  "portable" {>= "v0.18~" & < "v0.19~"}
  "portable_mpmc_queue"
  "portable_ws_deque" {>= "v0.18~" & < "v0.19~"}
  "ppx_jane" {>= "v0.18~" & < "v0.19~"}
  "unboxed" {>= "v0.18~" & < "v0.19~"}
  "unboxed_datatypes"
  "unique" {>= "v0.18~" & < "v0.19~"}
  "vec"
  "base-threads"
  "dune" {>= "3.17.0"}
]
available: arch != "x86_32"
synopsis: "OxCaml Parallelism"
description: "
 Parallelism infrastructure.
"
