opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/janestreet/parallel"
bug-reports: "https://github.com/janestreet/parallel/issues"
dev-repo: "git+https://github.com/janestreet/parallel.git"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/parallel/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.5.0"}
  "async"
  "await"
  "base"
  "base_bigstring"
  "bignum"
  "concurrent"
  "core"
  "expect_test_helpers_core"
  "handled_effect"
  "portable"
  "portable_mpmc_queue"
  "portable_ws_deque"
  "ppx_jane"
  "unboxed"
  "unboxed_datatypes"
  "unique"
  "vec"
  "base-threads"
  "dune"                     {>= "3.17.0"}
]
available: arch != "x86_32"
synopsis: "OxCaml Parallelism"
description: "
 Parallelism infrastructure.
"
